from . import sale_fun
from . import inventory_fun
from . import purchase_fun
from . import invoice_fun
from . import contacts_fun
from . import setting_inherit
from . import user_zalo
from . import res_config_settings
from . import authorization_zalo
from . import test_send_dis
from . import sale_confirm_order